package xxfinalcactbank.oracle.apps.fnd.cactbank.schema.server.common;

import oracle.jbo.common.JboResourceBundle;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public class xxCactBankCreateEOImplMsgBundle extends JboResourceBundle {
    static final Object[][] sMessageStrings = 
    {
{ "PerCountry_Rule_0", "Please enter valid Country" },
{ "ResDistrict_Rule_0", "Please enter valid District" },
{ "EmailId_Rule_2", "please enter a valid E-mail id" },
{ "ResPincode_Rule_1", "please enter valid pincode" },
{ "EmailId_Rule_0", "please enter a valid E-mail id" },
{ "PerPincode_Rule_0", "please enter a valid Pincode" },
{ "MobileNo_Rule_1", "please enter valid mobile no" },
{ "RefName_Rule_0", "Please enter valid name" },
{ "Pan_Rule_1", "Please enter valid PAN" },
{ "ResPincode_Rule_0", "please enter a valid Pincode" },
{ "PerCity_Rule_0", "Please enter valid City" },
{ "ResCity_Rule_0", "Please enter valid City" },
{ "PerState_Rule_0", "Please enter valid State" },
{ "PerAddress2_Rule_0", "Please enter valid Address line" },
{ "LastName_Rule_0", "Please enter valid name" },
{ "PerDistrict_Rule_0", "Please enter valid District" },
{ "ResState_Rule_0", "Please enter valid State" },
{ "EmailId_Rule_1", "please enter a valid E-mail id" },
{ "Pan_Rule_0", "Please enter valid PAN" },
{ "ResAddress2_Rule_0", "Please enter valid Address line" },
{ "FirstName_Rule_0", "Please enter valid name" },
{ "MobileNo_Rule_0", "please enter valid phone number" },
{ "ResCountry_Rule_0", "Please enter valid Country" },
{ "PerPincode_Rule_1", "Please enter valid Pincode" },
{ "MiddleName_Rule_0", "Please enter valid name" }};

    /**This is the default constructor (do not remove)
     */
    public xxCactBankCreateEOImplMsgBundle() {
    }

    /**@return an array of key-value pairs.
     */
    public Object[][] getContents() {
        return super.getMergedArray(sMessageStrings, super.getContents());
    }
}
