package xxfinalcactbank.oracle.apps.fnd.cactbank.schema.server.common;

import oracle.jbo.common.JboResourceBundle;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public class xxCactBankCreateEOImplMsgBundle extends JboResourceBundle {


    static final Object[][] sMessageStrings = 
    {
{ "EmailId_Rule_0", "please enter a valid E-mail id" },
{ "EmailId_Rule_1", "please enter a valid E-mail id" }};

    /**This is the default constructor (do not remove)
     */
    public xxCactBankCreateEOImplMsgBundle() {
    }

    /**@return an array of key-value pairs.
     */
    public Object[][] getContents() {
        return super.getMergedArray(sMessageStrings, super.getContents());
    }
}
