package xxfinalcactbank.oracle.apps.fnd.cactbank.schema.server;

import oracle.apps.fnd.framework.server.OAEntityCache;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class xxCactBankCreateEOCollImpl extends OAEntityCache {
    /**This is the default constructor (do not remove)
     */
    public xxCactBankCreateEOCollImpl() {
    }
}
