package xxfinalcactbank.oracle.apps.fnd.cactbank.lov.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class xxCactBankStatesVORowImpl extends OAViewRowImpl {
    public static final int COUNTRY2ID = 0;
    public static final int STATE2ID = 1;

    /**This is the default constructor (do not remove)
     */
    public xxCactBankStatesVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute Country2Id
     */
    public Number getCountry2Id() {
        return (Number) getAttributeInternal(COUNTRY2ID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Country2Id
     */
    public void setCountry2Id(Number value) {
        setAttributeInternal(COUNTRY2ID, value);
    }

    /**Gets the attribute value for the calculated attribute State2Id
     */
    public String getState2Id() {
        return (String) getAttributeInternal(STATE2ID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute State2Id
     */
    public void setState2Id(String value) {
        setAttributeInternal(STATE2ID, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case COUNTRY2ID:
            return getCountry2Id();
        case STATE2ID:
            return getState2Id();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case COUNTRY2ID:
            setCountry2Id((Number)value);
            return;
        case STATE2ID:
            setState2Id((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
