package xxfinalcactbank.oracle.apps.fnd.cactbank.poplist.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class xxCactBankBranchVORowImpl extends OAViewRowImpl {
    public static final int CITYNAME = 0;
    public static final int BRANCHNAME = 1;
    public static final int LNAME = 2;
    public static final int LANME = 3;
    public static final int BRANCHID = 4;
    public static final int CITYID = 5;

    /**This is the default constructor (do not remove)
     */
    public xxCactBankBranchVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute CityName
     */
    public String getCityName() {
        return (String) getAttributeInternal(CITYNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CityName
     */
    public void setCityName(String value) {
        setAttributeInternal(CITYNAME, value);
    }

    /**Gets the attribute value for the calculated attribute BranchName
     */
    public String getBranchName() {
        return (String) getAttributeInternal(BRANCHNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute BranchName
     */
    public void setBranchName(String value) {
        setAttributeInternal(BRANCHNAME, value);
    }

    /**Gets the attribute value for the calculated attribute Lname
     */
    public String getLname() {
        return (String) getAttributeInternal(LNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Lname
     */
    public void setLname(String value) {
        setAttributeInternal(LNAME, value);
    }

    /**Gets the attribute value for the calculated attribute Lanme
     */
    public String getLanme() {
        return (String) getAttributeInternal(LANME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Lanme
     */
    public void setLanme(String value) {
        setAttributeInternal(LANME, value);
    }

    /**Gets the attribute value for the calculated attribute BranchId
     */
    public Number getBranchId() {
        return (Number) getAttributeInternal(BRANCHID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute BranchId
     */
    public void setBranchId(Number value) {
        setAttributeInternal(BRANCHID, value);
    }

    /**Gets the attribute value for the calculated attribute CityId
     */
    public Number getCityId() {
        return (Number) getAttributeInternal(CITYID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CityId
     */
    public void setCityId(Number value) {
        setAttributeInternal(CITYID, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case CITYNAME:
            return getCityName();
        case BRANCHNAME:
            return getBranchName();
        case LNAME:
            return getLname();
        case LANME:
            return getLanme();
        case BRANCHID:
            return getBranchId();
        case CITYID:
            return getCityId();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case CITYNAME:
            setCityName((String)value);
            return;
        case BRANCHNAME:
            setBranchName((String)value);
            return;
        case LNAME:
            setLname((String)value);
            return;
        case LANME:
            setLanme((String)value);
            return;
        case BRANCHID:
            setBranchId((Number)value);
            return;
        case CITYID:
            setCityId((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
