package xxfinalcactbank.oracle.apps.fnd.cactbank.poplist.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class xxCactBankCityVORowImpl extends OAViewRowImpl {
    public static final int CITYID = 0;
    public static final int CITYNAME = 1;
    public static final int LNAME = 2;

    /**This is the default constructor (do not remove)
     */
    public xxCactBankCityVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute CityId
     */
    public Number getCityId() {
        return (Number) getAttributeInternal(CITYID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CityId
     */
    public void setCityId(Number value) {
        setAttributeInternal(CITYID, value);
    }

    /**Gets the attribute value for the calculated attribute CityName
     */
    public String getCityName() {
        return (String) getAttributeInternal(CITYNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CityName
     */
    public void setCityName(String value) {
        setAttributeInternal(CITYNAME, value);
    }

    /**Gets the attribute value for the calculated attribute Lname
     */
    public String getLname() {
        return (String) getAttributeInternal(LNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Lname
     */
    public void setLname(String value) {
        setAttributeInternal(LNAME, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case CITYID:
            return getCityId();
        case CITYNAME:
            return getCityName();
        case LNAME:
            return getLname();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case CITYID:
            setCityId((Number)value);
            return;
        case CITYNAME:
            setCityName((String)value);
            return;
        case LNAME:
            setLname((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
