package xxfinalcactbank.oracle.apps.fnd.cactbank.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.RowID;
import oracle.jbo.server.AttributeDefImpl;

import xxfinalcactbank.oracle.apps.fnd.cactbank.schema.server.xxcactTxnTestEOImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class xxcactTxnTestVO1RowImpl extends OAViewRowImpl {
    public static final int SNO = 0;
    public static final int TRANSACTIONTYPE = 1;
    public static final int TRANSACTIONID = 2;
    public static final int ACCNO = 3;
    public static final int TRANSFERACCNO = 4;
    public static final int AMOUNTFROMACC = 5;
    public static final int CREDIT = 6;
    public static final int DEBIT = 7;
    public static final int BALANCE = 8;
    public static final int ATTRIBUTE1 = 9;
    public static final int ATTRIBUTE2 = 10;
    public static final int ATTRIBUTE3 = 11;
    public static final int ATTRIBUTE4 = 12;
    public static final int ATTRIBUTE5 = 13;
    public static final int ATTRIBUTE6 = 14;
    public static final int ATTRIBUTE7 = 15;
    public static final int ATTRIBUTE8 = 16;
    public static final int ATTRIBUTE9 = 17;
    public static final int ATTRIBUTE10 = 18;
    public static final int LASTUPDATEDATE = 19;
    public static final int LASTUPDATEDBY = 20;
    public static final int CREATIONDATE = 21;
    public static final int CREATEDBY = 22;
    public static final int LASTUPDATELOGIN = 23;
    public static final int ROWID = 24;

    /**This is the default constructor (do not remove)
     */
    public xxcactTxnTestVO1RowImpl() {
    }

    /**Gets xxcactTxnTestEO entity object.
     */
    public xxcactTxnTestEOImpl getxxcactTxnTestEO() {
        return (xxcactTxnTestEOImpl)getEntity(0);
    }

    /**Gets the attribute value for SNO using the alias name Sno
     */
    public Number getSno() {
        return (Number) getAttributeInternal(SNO);
    }

    /**Sets <code>value</code> as attribute value for SNO using the alias name Sno
     */
    public void setSno(Number value) {
        setAttributeInternal(SNO, value);
    }

    /**Gets the attribute value for TRANSACTION_TYPE using the alias name TransactionType
     */
    public String getTransactionType() {
        return (String) getAttributeInternal(TRANSACTIONTYPE);
    }

    /**Sets <code>value</code> as attribute value for TRANSACTION_TYPE using the alias name TransactionType
     */
    public void setTransactionType(String value) {
        setAttributeInternal(TRANSACTIONTYPE, value);
    }

    /**Gets the attribute value for TRANSACTION_ID using the alias name TransactionId
     */
    public Number getTransactionId() {
        return (Number) getAttributeInternal(TRANSACTIONID);
    }

    /**Sets <code>value</code> as attribute value for TRANSACTION_ID using the alias name TransactionId
     */
    public void setTransactionId(Number value) {
        setAttributeInternal(TRANSACTIONID, value);
    }

    /**Gets the attribute value for ACC_NO using the alias name AccNo
     */
    public Number getAccNo() {
        return (Number) getAttributeInternal(ACCNO);
    }

    /**Sets <code>value</code> as attribute value for ACC_NO using the alias name AccNo
     */
    public void setAccNo(Number value) {
        setAttributeInternal(ACCNO, value);
    }

    /**Gets the attribute value for TRANSFER_ACC_NO using the alias name TransferAccNo
     */
    public Number getTransferAccNo() {
        return (Number) getAttributeInternal(TRANSFERACCNO);
    }

    /**Sets <code>value</code> as attribute value for TRANSFER_ACC_NO using the alias name TransferAccNo
     */
    public void setTransferAccNo(Number value) {
        setAttributeInternal(TRANSFERACCNO, value);
    }

    /**Gets the attribute value for AMOUNT_FROM_ACC using the alias name AmountFromAcc
     */
    public Number getAmountFromAcc() {
        return (Number) getAttributeInternal(AMOUNTFROMACC);
    }

    /**Sets <code>value</code> as attribute value for AMOUNT_FROM_ACC using the alias name AmountFromAcc
     */
    public void setAmountFromAcc(Number value) {
        setAttributeInternal(AMOUNTFROMACC, value);
    }

    /**Gets the attribute value for CREDIT using the alias name Credit
     */
    public Number getCredit() {
        return (Number) getAttributeInternal(CREDIT);
    }

    /**Sets <code>value</code> as attribute value for CREDIT using the alias name Credit
     */
    public void setCredit(Number value) {
        setAttributeInternal(CREDIT, value);
    }

    /**Gets the attribute value for DEBIT using the alias name Debit
     */
    public Number getDebit() {
        return (Number) getAttributeInternal(DEBIT);
    }

    /**Sets <code>value</code> as attribute value for DEBIT using the alias name Debit
     */
    public void setDebit(Number value) {
        setAttributeInternal(DEBIT, value);
    }

    /**Gets the attribute value for BALANCE using the alias name Balance
     */
    public Number getBalance() {
        return (Number) getAttributeInternal(BALANCE);
    }

    /**Sets <code>value</code> as attribute value for BALANCE using the alias name Balance
     */
    public void setBalance(Number value) {
        setAttributeInternal(BALANCE, value);
    }

    /**Gets the attribute value for ATTRIBUTE1 using the alias name Attribute1
     */
    public String getAttribute1() {
        return (String) getAttributeInternal(ATTRIBUTE1);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE1 using the alias name Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**Gets the attribute value for ATTRIBUTE2 using the alias name Attribute2
     */
    public String getAttribute2() {
        return (String) getAttributeInternal(ATTRIBUTE2);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE2 using the alias name Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**Gets the attribute value for ATTRIBUTE3 using the alias name Attribute3
     */
    public String getAttribute3() {
        return (String) getAttributeInternal(ATTRIBUTE3);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE3 using the alias name Attribute3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**Gets the attribute value for ATTRIBUTE4 using the alias name Attribute4
     */
    public String getAttribute4() {
        return (String) getAttributeInternal(ATTRIBUTE4);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE4 using the alias name Attribute4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**Gets the attribute value for ATTRIBUTE5 using the alias name Attribute5
     */
    public String getAttribute5() {
        return (String) getAttributeInternal(ATTRIBUTE5);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE5 using the alias name Attribute5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**Gets the attribute value for ATTRIBUTE6 using the alias name Attribute6
     */
    public String getAttribute6() {
        return (String) getAttributeInternal(ATTRIBUTE6);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE6 using the alias name Attribute6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**Gets the attribute value for ATTRIBUTE7 using the alias name Attribute7
     */
    public String getAttribute7() {
        return (String) getAttributeInternal(ATTRIBUTE7);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE7 using the alias name Attribute7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**Gets the attribute value for ATTRIBUTE8 using the alias name Attribute8
     */
    public String getAttribute8() {
        return (String) getAttributeInternal(ATTRIBUTE8);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE8 using the alias name Attribute8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**Gets the attribute value for ATTRIBUTE9 using the alias name Attribute9
     */
    public String getAttribute9() {
        return (String) getAttributeInternal(ATTRIBUTE9);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE9 using the alias name Attribute9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**Gets the attribute value for ATTRIBUTE10 using the alias name Attribute10
     */
    public String getAttribute10() {
        return (String) getAttributeInternal(ATTRIBUTE10);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE10 using the alias name Attribute10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**Gets the attribute value for CREATION_DATE using the alias name CreationDate
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**Gets the attribute value for CREATED_BY using the alias name CreatedBy
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**Sets <code>value</code> as attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**Gets the attribute value for ROWID using the alias name RowID
     */
    public RowID getRowID() {
        return (RowID) getAttributeInternal(ROWID);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case SNO:
            return getSno();
        case TRANSACTIONTYPE:
            return getTransactionType();
        case TRANSACTIONID:
            return getTransactionId();
        case ACCNO:
            return getAccNo();
        case TRANSFERACCNO:
            return getTransferAccNo();
        case AMOUNTFROMACC:
            return getAmountFromAcc();
        case CREDIT:
            return getCredit();
        case DEBIT:
            return getDebit();
        case BALANCE:
            return getBalance();
        case ATTRIBUTE1:
            return getAttribute1();
        case ATTRIBUTE2:
            return getAttribute2();
        case ATTRIBUTE3:
            return getAttribute3();
        case ATTRIBUTE4:
            return getAttribute4();
        case ATTRIBUTE5:
            return getAttribute5();
        case ATTRIBUTE6:
            return getAttribute6();
        case ATTRIBUTE7:
            return getAttribute7();
        case ATTRIBUTE8:
            return getAttribute8();
        case ATTRIBUTE9:
            return getAttribute9();
        case ATTRIBUTE10:
            return getAttribute10();
        case LASTUPDATEDATE:
            return getLastUpdateDate();
        case LASTUPDATEDBY:
            return getLastUpdatedBy();
        case CREATIONDATE:
            return getCreationDate();
        case CREATEDBY:
            return getCreatedBy();
        case LASTUPDATELOGIN:
            return getLastUpdateLogin();
        case ROWID:
            return getRowID();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case SNO:
            setSno((Number)value);
            return;
        case TRANSACTIONTYPE:
            setTransactionType((String)value);
            return;
        case TRANSACTIONID:
            setTransactionId((Number)value);
            return;
        case ACCNO:
            setAccNo((Number)value);
            return;
        case TRANSFERACCNO:
            setTransferAccNo((Number)value);
            return;
        case AMOUNTFROMACC:
            setAmountFromAcc((Number)value);
            return;
        case CREDIT:
            setCredit((Number)value);
            return;
        case DEBIT:
            setDebit((Number)value);
            return;
        case BALANCE:
            setBalance((Number)value);
            return;
        case ATTRIBUTE1:
            setAttribute1((String)value);
            return;
        case ATTRIBUTE2:
            setAttribute2((String)value);
            return;
        case ATTRIBUTE3:
            setAttribute3((String)value);
            return;
        case ATTRIBUTE4:
            setAttribute4((String)value);
            return;
        case ATTRIBUTE5:
            setAttribute5((String)value);
            return;
        case ATTRIBUTE6:
            setAttribute6((String)value);
            return;
        case ATTRIBUTE7:
            setAttribute7((String)value);
            return;
        case ATTRIBUTE8:
            setAttribute8((String)value);
            return;
        case ATTRIBUTE9:
            setAttribute9((String)value);
            return;
        case ATTRIBUTE10:
            setAttribute10((String)value);
            return;
        case LASTUPDATEDATE:
            setLastUpdateDate((Date)value);
            return;
        case LASTUPDATEDBY:
            setLastUpdatedBy((Number)value);
            return;
        case CREATIONDATE:
            setCreationDate((Date)value);
            return;
        case CREATEDBY:
            setCreatedBy((Number)value);
            return;
        case LASTUPDATELOGIN:
            setLastUpdateLogin((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
