package xxfinalcactbank.oracle.apps.fnd.cactbank.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class xxcactBankValiVORowImpl extends OAViewRowImpl {
    public static final int USERID = 0;
    public static final int ACCNO = 1;
    public static final int ACCHOLDERNAME = 2;
    public static final int BALANCE = 3;

    /**This is the default constructor (do not remove)
     */
    public xxcactBankValiVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute UserId
     */
    public String getUserId() {
        return (String) getAttributeInternal(USERID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute UserId
     */
    public void setUserId(String value) {
        setAttributeInternal(USERID, value);
    }

    /**Gets the attribute value for the calculated attribute AccNo
     */
    public Number getAccNo() {
        return (Number) getAttributeInternal(ACCNO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute AccNo
     */
    public void setAccNo(Number value) {
        setAttributeInternal(ACCNO, value);
    }

    /**Gets the attribute value for the calculated attribute AccHolderName
     */
    public String getAccHolderName() {
        return (String) getAttributeInternal(ACCHOLDERNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute AccHolderName
     */
    public void setAccHolderName(String value) {
        setAttributeInternal(ACCHOLDERNAME, value);
    }

    /**Gets the attribute value for the calculated attribute Balance
     */
    public Number getBalance() {
        return (Number) getAttributeInternal(BALANCE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Balance
     */
    public void setBalance(Number value) {
        setAttributeInternal(BALANCE, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case USERID:
            return getUserId();
        case ACCNO:
            return getAccNo();
        case ACCHOLDERNAME:
            return getAccHolderName();
        case BALANCE:
            return getBalance();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case USERID:
            setUserId((String)value);
            return;
        case ACCNO:
            setAccNo((Number)value);
            return;
        case ACCHOLDERNAME:
            setAccHolderName((String)value);
            return;
        case BALANCE:
            setBalance((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
