package xxfinalcactbank.oracle.apps.fnd.cactbank.server;

import oracle.apps.fnd.framework.server.OAViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class xxcactTxnTestVOImpl extends OAViewObjectImpl {
    /**This is the default constructor (do not remove)
     */
     
     public void initQuery(String par)
     {
         if ((par != null) &&
         (!("".equals(par.trim()))))
                 {
             //Number ordNum = null;
           
            
             System.out.println("Accno Berfore where"+par);
            setWhereClause("Acc_no = :1");
             setOrderByClause("sno desc");
             System.out.println("Accno After where"+par);
             setWhereClauseParams(null); // Always reset
             setWhereClauseParam(0, par);
           
             executeQuery();
     
         } // end initQuery()
     }
    public xxcactTxnTestVOImpl() {
    }
}
