package xxfinalcactbank.oracle.apps.fnd.cactbank.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Number;
import oracle.jbo.domain.RowID;
import oracle.jbo.server.AttributeDefImpl;

import xxfinalcactbank.oracle.apps.fnd.cactbank.schema.server.XxCactAttachmentEOImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class xxCactAttachmentVORowImpl extends OAViewRowImpl {
    public static final int ATTACHMENTID = 0;
    public static final int ROWID = 1;
    public static final int USERID = 2;

    /**This is the default constructor (do not remove)
     */
    public xxCactAttachmentVORowImpl() {
    }

    /**Gets XxCactAttachmentEO entity object.
     */
    public XxCactAttachmentEOImpl getXxCactAttachmentEO() {
        return (XxCactAttachmentEOImpl)getEntity(0);
    }

    /**Gets the attribute value for ATTACHMENT_ID using the alias name AttachmentId
     */
    public Number getAttachmentId() {
        return (Number) getAttributeInternal(ATTACHMENTID);
    }

    /**Sets <code>value</code> as attribute value for ATTACHMENT_ID using the alias name AttachmentId
     */
    public void setAttachmentId(Number value) {
        setAttributeInternal(ATTACHMENTID, value);
    }

    /**Gets the attribute value for ROWID using the alias name RowID
     */
    public RowID getRowID() {
        return (RowID) getAttributeInternal(ROWID);
    }

    /**Gets the attribute value for USER_ID using the alias name UserId
     */
    public String getUserId() {
        return (String) getAttributeInternal(USERID);
    }

    /**Sets <code>value</code> as attribute value for USER_ID using the alias name UserId
     */
    public void setUserId(String value) {
        setAttributeInternal(USERID, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ATTACHMENTID:
            return getAttachmentId();
        case ROWID:
            return getRowID();
        case USERID:
            return getUserId();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ATTACHMENTID:
            setAttachmentId((Number)value);
            return;
        case USERID:
            setUserId((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
