package xxfinalcactbank.oracle.apps.fnd.cactbank.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class xxCactBankAccTypeVORowImpl extends OAViewRowImpl {
    public static final int ACCOUNTTYPE = 0;

    /**This is the default constructor (do not remove)
     */
    public xxCactBankAccTypeVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute AccountType
     */
    public String getAccountType() {
        return (String) getAttributeInternal(ACCOUNTTYPE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute AccountType
     */
    public void setAccountType(String value) {
        setAttributeInternal(ACCOUNTTYPE, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ACCOUNTTYPE:
            return getAccountType();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ACCOUNTTYPE:
            setAccountType((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
