package xxfinalcactbank.oracle.apps.fnd.cactbank.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class xxCactBankDetVORowImpl extends OAViewRowImpl {
    public static final int USERID = 0;
    public static final int ACCNO = 1;
    public static final int ACCOUNTHOLDERNAME = 2;
    public static final int BRANCH = 3;
    public static final int EMAILID = 4;
    public static final int MOBILENO = 5;
    public static final int BALANCE = 6;

    /**This is the default constructor (do not remove)
     */
    public xxCactBankDetVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute UserId
     */
    public String getUserId() {
        return (String) getAttributeInternal(USERID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute UserId
     */
    public void setUserId(String value) {
        setAttributeInternal(USERID, value);
    }

    /**Gets the attribute value for the calculated attribute AccNo
     */
    public Number getAccNo() {
        return (Number) getAttributeInternal(ACCNO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute AccNo
     */
    public void setAccNo(Number value) {
        setAttributeInternal(ACCNO, value);
    }

    /**Gets the attribute value for the calculated attribute AccountHolderName
     */
    public String getAccountHolderName() {
        return (String) getAttributeInternal(ACCOUNTHOLDERNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute AccountHolderName
     */
    public void setAccountHolderName(String value) {
        setAttributeInternal(ACCOUNTHOLDERNAME, value);
    }

    /**Gets the attribute value for the calculated attribute Branch
     */
    public String getBranch() {
        return (String) getAttributeInternal(BRANCH);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Branch
     */
    public void setBranch(String value) {
        setAttributeInternal(BRANCH, value);
    }

    /**Gets the attribute value for the calculated attribute EmailId
     */
    public String getEmailId() {
        return (String) getAttributeInternal(EMAILID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EmailId
     */
    public void setEmailId(String value) {
        setAttributeInternal(EMAILID, value);
    }

    /**Gets the attribute value for the calculated attribute MobileNo
     */
    public Number getMobileNo() {
        return (Number) getAttributeInternal(MOBILENO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute MobileNo
     */
    public void setMobileNo(Number value) {
        setAttributeInternal(MOBILENO, value);
    }

    /**Gets the attribute value for the calculated attribute Balance
     */
    public Number getBalance() {
        return (Number) getAttributeInternal(BALANCE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Balance
     */
    public void setBalance(Number value) {
        setAttributeInternal(BALANCE, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case USERID:
            return getUserId();
        case ACCNO:
            return getAccNo();
        case ACCOUNTHOLDERNAME:
            return getAccountHolderName();
        case BRANCH:
            return getBranch();
        case EMAILID:
            return getEmailId();
        case MOBILENO:
            return getMobileNo();
        case BALANCE:
            return getBalance();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case USERID:
            setUserId((String)value);
            return;
        case ACCNO:
            setAccNo((Number)value);
            return;
        case ACCOUNTHOLDERNAME:
            setAccountHolderName((String)value);
            return;
        case BRANCH:
            setBranch((String)value);
            return;
        case EMAILID:
            setEmailId((String)value);
            return;
        case MOBILENO:
            setMobileNo((Number)value);
            return;
        case BALANCE:
            setBalance((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
