package xxfinalcactbank.oracle.apps.fnd.cactbank.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class xxCactBankOccTypeVORowImpl extends OAViewRowImpl {
    public static final int OCCUPATIONTYPE = 0;

    /**This is the default constructor (do not remove)
     */
    public xxCactBankOccTypeVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute OccupationType
     */
    public String getOccupationType() {
        return (String) getAttributeInternal(OCCUPATIONTYPE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute OccupationType
     */
    public void setOccupationType(String value) {
        setAttributeInternal(OCCUPATIONTYPE, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case OCCUPATIONTYPE:
            return getOccupationType();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case OCCUPATIONTYPE:
            setOccupationType((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
