package xxfinalcactbank.oracle.apps.fnd.cactbank.server;

import oracle.apps.fnd.framework.server.OAViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class xxCactBankDetVOImpl extends OAViewObjectImpl {
    /**This is the default constructor (do not remove)
     */
     
     public void initQuery(String userid)
           {
           if ((userid != null) &&
           (!("".equals(userid.trim()))))
           {
           // Do the following conversion for type consistency.

           setWhereClause("USER_ID = :1");
           setWhereClauseParams(null); // Always reset
           setWhereClauseParam(0, userid);
           executeQuery();
           }
           }
    public xxCactBankDetVOImpl() {
    }
}
