package xxfinalcactbank.oracle.apps.fnd.cactbank.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import xxfinalcactbank.oracle.apps.fnd.cactbank.schema.server.xxCactBankCreateEOImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class xxCactBankCreateVORowImpl extends OAViewRowImpl {
    public static final int USERID = 0;
    public static final int PASSWORD = 1;
    public static final int FIRSTNAME = 2;
    public static final int MIDDLENAME = 3;
    public static final int LASTNAME = 4;
    public static final int MOBILENO = 5;
    public static final int EMAILID = 6;
    public static final int REFNAME = 7;
    public static final int DOB = 8;
    public static final int GENDER = 9;
    public static final int PAN = 10;
    public static final int MARITAL = 11;
    public static final int ANNUALINCOME = 12;
    public static final int OCCUPATION = 13;
    public static final int RESADDRESS1 = 14;
    public static final int RESADDRESS2 = 15;
    public static final int RESCITY = 16;
    public static final int RESDISTRICT = 17;
    public static final int RESSTATE = 18;
    public static final int RESCOUNTRY = 19;
    public static final int RESPINCODE = 20;
    public static final int PERADDRESS1 = 21;
    public static final int PERADDRESS2 = 22;
    public static final int PERCITY = 23;
    public static final int PERDISTRICT = 24;
    public static final int PERSTATE = 25;
    public static final int PERCOUNTRY = 26;
    public static final int PERPINCODE = 27;
    public static final int ACCTYPE = 28;
    public static final int PREFCITY = 29;
    public static final int BRANCH = 30;
    public static final int DOCNAME = 31;
    public static final int APPLDATE = 32;
    public static final int MANAGED = 33;
    public static final int ADDRESS1 = 34;
    public static final int ADDRESS2 = 35;
    public static final int CITY = 36;
    public static final int DISTRICT = 37;
    public static final int COUNTRY = 38;
    public static final int PINCODE = 39;
    public static final int STATE = 40;
    public static final int PERADD = 41;
    public static final int PERADD1 = 42;
    public static final int PERADDRN = 43;
    public static final int PERADDRN1 = 44;

    /**This is the default constructor (do not remove)
     */
    public xxCactBankCreateVORowImpl() {
    }

    /**Gets xxCactBankCreateEO entity object.
     */
    public xxCactBankCreateEOImpl getxxCactBankCreateEO() {
        return (xxCactBankCreateEOImpl)getEntity(0);
    }

    /**Gets the attribute value for USER_ID using the alias name UserId
     */
    public String getUserId() {
        return (String) getAttributeInternal(USERID);
    }

    /**Sets <code>value</code> as attribute value for USER_ID using the alias name UserId
     */
    public void setUserId(String value) {
        setAttributeInternal(USERID, value);
    }

    /**Gets the attribute value for PASSWORD using the alias name Password
     */
    public String getPassword() {
        return (String) getAttributeInternal(PASSWORD);
    }

    /**Sets <code>value</code> as attribute value for PASSWORD using the alias name Password
     */
    public void setPassword(String value) {
        setAttributeInternal(PASSWORD, value);
    }

    /**Gets the attribute value for FIRST_NAME using the alias name FirstName
     */
    public String getFirstName() {
        return (String) getAttributeInternal(FIRSTNAME);
    }

    /**Sets <code>value</code> as attribute value for FIRST_NAME using the alias name FirstName
     */
    public void setFirstName(String value) {
        setAttributeInternal(FIRSTNAME, value);
    }

    /**Gets the attribute value for MIDDLE_NAME using the alias name MiddleName
     */
    public String getMiddleName() {
        return (String) getAttributeInternal(MIDDLENAME);
    }

    /**Sets <code>value</code> as attribute value for MIDDLE_NAME using the alias name MiddleName
     */
    public void setMiddleName(String value) {
        setAttributeInternal(MIDDLENAME, value);
    }

    /**Gets the attribute value for LAST_NAME using the alias name LastName
     */
    public String getLastName() {
        return (String) getAttributeInternal(LASTNAME);
    }

    /**Sets <code>value</code> as attribute value for LAST_NAME using the alias name LastName
     */
    public void setLastName(String value) {
        setAttributeInternal(LASTNAME, value);
    }

    /**Gets the attribute value for MOBILE_NO using the alias name MobileNo
     */
    public Number getMobileNo() {
        return (Number) getAttributeInternal(MOBILENO);
    }

    /**Sets <code>value</code> as attribute value for MOBILE_NO using the alias name MobileNo
     */
    public void setMobileNo(Number value) {
        setAttributeInternal(MOBILENO, value);
    }

    /**Gets the attribute value for EMAIL_ID using the alias name EmailId
     */
    public String getEmailId() {
        return (String) getAttributeInternal(EMAILID);
    }

    /**Sets <code>value</code> as attribute value for EMAIL_ID using the alias name EmailId
     */
    public void setEmailId(String value) {
        setAttributeInternal(EMAILID, value);
    }

    /**Gets the attribute value for REF_NAME using the alias name RefName
     */
    public String getRefName() {
        return (String) getAttributeInternal(REFNAME);
    }

    /**Sets <code>value</code> as attribute value for REF_NAME using the alias name RefName
     */
    public void setRefName(String value) {
        setAttributeInternal(REFNAME, value);
    }

    /**Gets the attribute value for DOB using the alias name Dob
     */
    public Date getDob() {
        return (Date) getAttributeInternal(DOB);
    }

    /**Sets <code>value</code> as attribute value for DOB using the alias name Dob
     */
    public void setDob(Date value) {
        setAttributeInternal(DOB, value);
    }

    /**Gets the attribute value for GENDER using the alias name Gender
     */
    public String getGender() {
        return (String) getAttributeInternal(GENDER);
    }

    /**Sets <code>value</code> as attribute value for GENDER using the alias name Gender
     */
    public void setGender(String value) {
        setAttributeInternal(GENDER, value);
    }

    /**Gets the attribute value for PAN using the alias name Pan
     */
    public String getPan() {
        return (String) getAttributeInternal(PAN);
    }

    /**Sets <code>value</code> as attribute value for PAN using the alias name Pan
     */
    public void setPan(String value) {
        setAttributeInternal(PAN, value);
    }

    /**Gets the attribute value for MARITAL using the alias name Marital
     */
    public String getMarital() {
        return (String) getAttributeInternal(MARITAL);
    }

    /**Sets <code>value</code> as attribute value for MARITAL using the alias name Marital
     */
    public void setMarital(String value) {
        setAttributeInternal(MARITAL, value);
    }

    /**Gets the attribute value for ANNUAL_INCOME using the alias name AnnualIncome
     */
    public String getAnnualIncome() {
        return (String) getAttributeInternal(ANNUALINCOME);
    }

    /**Sets <code>value</code> as attribute value for ANNUAL_INCOME using the alias name AnnualIncome
     */
    public void setAnnualIncome(String value) {
        setAttributeInternal(ANNUALINCOME, value);
    }

    /**Gets the attribute value for OCCUPATION using the alias name Occupation
     */
    public String getOccupation() {
        return (String) getAttributeInternal(OCCUPATION);
    }

    /**Sets <code>value</code> as attribute value for OCCUPATION using the alias name Occupation
     */
    public void setOccupation(String value) {
        setAttributeInternal(OCCUPATION, value);
    }

    /**Gets the attribute value for RES_ADDRESS1 using the alias name ResAddress1
     */
    public String getResAddress1() {
        return (String) getAttributeInternal(RESADDRESS1);
    }

    /**Sets <code>value</code> as attribute value for RES_ADDRESS1 using the alias name ResAddress1
     */
    public void setResAddress1(String value) {
        setAttributeInternal(RESADDRESS1, value);
    }

    /**Gets the attribute value for RES_ADDRESS2 using the alias name ResAddress2
     */
    public String getResAddress2() {
        return (String) getAttributeInternal(RESADDRESS2);
    }

    /**Sets <code>value</code> as attribute value for RES_ADDRESS2 using the alias name ResAddress2
     */
    public void setResAddress2(String value) {
        setAttributeInternal(RESADDRESS2, value);
    }

    /**Gets the attribute value for RES_CITY using the alias name ResCity
     */
    public String getResCity() {
        return (String) getAttributeInternal(RESCITY);
    }

    /**Sets <code>value</code> as attribute value for RES_CITY using the alias name ResCity
     */
    public void setResCity(String value) {
        setAttributeInternal(RESCITY, value);
    }

    /**Gets the attribute value for RES_DISTRICT using the alias name ResDistrict
     */
    public String getResDistrict() {
        return (String) getAttributeInternal(RESDISTRICT);
    }

    /**Sets <code>value</code> as attribute value for RES_DISTRICT using the alias name ResDistrict
     */
    public void setResDistrict(String value) {
        setAttributeInternal(RESDISTRICT, value);
    }

    /**Gets the attribute value for RES_STATE using the alias name ResState
     */
    public String getResState() {
        return (String) getAttributeInternal(RESSTATE);
    }

    /**Sets <code>value</code> as attribute value for RES_STATE using the alias name ResState
     */
    public void setResState(String value) {
        setAttributeInternal(RESSTATE, value);
    }

    /**Gets the attribute value for RES_COUNTRY using the alias name ResCountry
     */
    public String getResCountry() {
        return (String) getAttributeInternal(RESCOUNTRY);
    }

    /**Sets <code>value</code> as attribute value for RES_COUNTRY using the alias name ResCountry
     */
    public void setResCountry(String value) {
        setAttributeInternal(RESCOUNTRY, value);
    }

    /**Gets the attribute value for RES_PINCODE using the alias name ResPincode
     */
    public Number getResPincode() {
        return (Number) getAttributeInternal(RESPINCODE);
    }

    /**Sets <code>value</code> as attribute value for RES_PINCODE using the alias name ResPincode
     */
    public void setResPincode(Number value) {
        setAttributeInternal(RESPINCODE, value);
    }

    /**Gets the attribute value for PER_ADDRESS1 using the alias name PerAddress1
     */
    public String getPerAddress1() {
        return (String) getAttributeInternal(PERADDRESS1);
    }

    /**Sets <code>value</code> as attribute value for PER_ADDRESS1 using the alias name PerAddress1
     */
    public void setPerAddress1(String value) {
        setAttributeInternal(PERADDRESS1, value);
    }

    /**Gets the attribute value for PER_ADDRESS2 using the alias name PerAddress2
     */
    public String getPerAddress2() {
        return (String) getAttributeInternal(PERADDRESS2);
    }

    /**Sets <code>value</code> as attribute value for PER_ADDRESS2 using the alias name PerAddress2
     */
    public void setPerAddress2(String value) {
        setAttributeInternal(PERADDRESS2, value);
    }

    /**Gets the attribute value for PER_CITY using the alias name PerCity
     */
    public String getPerCity() {
        return (String) getAttributeInternal(PERCITY);
    }

    /**Sets <code>value</code> as attribute value for PER_CITY using the alias name PerCity
     */
    public void setPerCity(String value) {
        setAttributeInternal(PERCITY, value);
    }

    /**Gets the attribute value for PER_DISTRICT using the alias name PerDistrict
     */
    public String getPerDistrict() {
        return (String) getAttributeInternal(PERDISTRICT);
    }

    /**Sets <code>value</code> as attribute value for PER_DISTRICT using the alias name PerDistrict
     */
    public void setPerDistrict(String value) {
        setAttributeInternal(PERDISTRICT, value);
    }

    /**Gets the attribute value for PER_STATE using the alias name PerState
     */
    public String getPerState() {
        return (String) getAttributeInternal(PERSTATE);
    }

    /**Sets <code>value</code> as attribute value for PER_STATE using the alias name PerState
     */
    public void setPerState(String value) {
        setAttributeInternal(PERSTATE, value);
    }

    /**Gets the attribute value for PER_COUNTRY using the alias name PerCountry
     */
    public String getPerCountry() {
        return (String) getAttributeInternal(PERCOUNTRY);
    }

    /**Sets <code>value</code> as attribute value for PER_COUNTRY using the alias name PerCountry
     */
    public void setPerCountry(String value) {
        setAttributeInternal(PERCOUNTRY, value);
    }

    /**Gets the attribute value for PER_PINCODE using the alias name PerPincode
     */
    public Number getPerPincode() {
        return (Number) getAttributeInternal(PERPINCODE);
    }

    /**Sets <code>value</code> as attribute value for PER_PINCODE using the alias name PerPincode
     */
    public void setPerPincode(Number value) {
        setAttributeInternal(PERPINCODE, value);
    }

    /**Gets the attribute value for ACC_TYPE using the alias name AccType
     */
    public String getAccType() {
        return (String) getAttributeInternal(ACCTYPE);
    }

    /**Sets <code>value</code> as attribute value for ACC_TYPE using the alias name AccType
     */
    public void setAccType(String value) {
        setAttributeInternal(ACCTYPE, value);
    }

    /**Gets the attribute value for PREF_CITY using the alias name PrefCity
     */
    public String getPrefCity() {
        return (String) getAttributeInternal(PREFCITY);
    }

    /**Sets <code>value</code> as attribute value for PREF_CITY using the alias name PrefCity
     */
    public void setPrefCity(String value) {
        setAttributeInternal(PREFCITY, value);
    }

    /**Gets the attribute value for BRANCH using the alias name Branch
     */
    public String getBranch() {
        return (String) getAttributeInternal(BRANCH);
    }

    /**Sets <code>value</code> as attribute value for BRANCH using the alias name Branch
     */
    public void setBranch(String value) {
        setAttributeInternal(BRANCH, value);
    }

    /**Gets the attribute value for DOC_NAME using the alias name DocName
     */
    public String getDocName() {
        return (String) getAttributeInternal(DOCNAME);
    }

    /**Sets <code>value</code> as attribute value for DOC_NAME using the alias name DocName
     */
    public void setDocName(String value) {
        setAttributeInternal(DOCNAME, value);
    }

    /**Gets the attribute value for APPL_DATE using the alias name ApplDate
     */
    public Date getApplDate() {
        return (Date) getAttributeInternal(APPLDATE);
    }

    /**Sets <code>value</code> as attribute value for APPL_DATE using the alias name ApplDate
     */
    public void setApplDate(Date value) {
        setAttributeInternal(APPLDATE, value);
    }

    /**Gets the attribute value for the calculated attribute managed
     */
    public Boolean getmanaged() {
        return (Boolean) getAttributeInternal(MANAGED);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute managed
     */
    public void setmanaged(Boolean value) {
        setAttributeInternal(MANAGED, value);
    }

    /**Gets the attribute value for the calculated attribute address1
     */
    public Boolean getaddress1() {
        return (Boolean) getAttributeInternal(ADDRESS1);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute address1
     */
    public void setaddress1(Boolean value) {
        setAttributeInternal(ADDRESS1, value);
    }

    /**Gets the attribute value for the calculated attribute address2
     */
    public Boolean getaddress2() {
        return (Boolean) getAttributeInternal(ADDRESS2);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute address2
     */
    public void setaddress2(Boolean value) {
        setAttributeInternal(ADDRESS2, value);
    }

    /**Gets the attribute value for the calculated attribute city
     */
    public Boolean getcity() {
        return (Boolean) getAttributeInternal(CITY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute city
     */
    public void setcity(Boolean value) {
        setAttributeInternal(CITY, value);
    }

    /**Gets the attribute value for the calculated attribute district
     */
    public Boolean getdistrict() {
        return (Boolean) getAttributeInternal(DISTRICT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute district
     */
    public void setdistrict(Boolean value) {
        setAttributeInternal(DISTRICT, value);
    }

    /**Gets the attribute value for the calculated attribute country
     */
    public Boolean getcountry() {
        return (Boolean) getAttributeInternal(COUNTRY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute country
     */
    public void setcountry(Boolean value) {
        setAttributeInternal(COUNTRY, value);
    }

    /**Gets the attribute value for the calculated attribute pincode
     */
    public Boolean getpincode() {
        return (Boolean) getAttributeInternal(PINCODE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute pincode
     */
    public void setpincode(Boolean value) {
        setAttributeInternal(PINCODE, value);
    }

    /**Gets the attribute value for the calculated attribute state
     */
    public Boolean getstate() {
        return (Boolean) getAttributeInternal(STATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute state
     */
    public void setstate(Boolean value) {
        setAttributeInternal(STATE, value);
    }

    /**Gets the attribute value for the calculated attribute peradd
     */
    public Boolean getperadd() {
        return (Boolean) getAttributeInternal(PERADD);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute peradd
     */
    public void setperadd(Boolean value) {
        setAttributeInternal(PERADD, value);
    }

    /**Gets the attribute value for the calculated attribute peradd1
     */
    public Boolean getperadd1() {
        return (Boolean) getAttributeInternal(PERADD1);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute peradd1
     */
    public void setperadd1(Boolean value) {
        setAttributeInternal(PERADD1, value);
    }

    /**Gets the attribute value for the calculated attribute peraddrn
     */
    public Boolean getperaddrn() {
        return (Boolean) getAttributeInternal(PERADDRN);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute peraddrn
     */
    public void setperaddrn(Boolean value) {
        setAttributeInternal(PERADDRN, value);
    }

    /**Gets the attribute value for the calculated attribute peraddrn1
     */
    public Boolean getperaddrn1() {
        return (Boolean) getAttributeInternal(PERADDRN1);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute peraddrn1
     */
    public void setperaddrn1(Boolean value) {
        setAttributeInternal(PERADDRN1, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case USERID:
            return getUserId();
        case PASSWORD:
            return getPassword();
        case FIRSTNAME:
            return getFirstName();
        case MIDDLENAME:
            return getMiddleName();
        case LASTNAME:
            return getLastName();
        case MOBILENO:
            return getMobileNo();
        case EMAILID:
            return getEmailId();
        case REFNAME:
            return getRefName();
        case DOB:
            return getDob();
        case GENDER:
            return getGender();
        case PAN:
            return getPan();
        case MARITAL:
            return getMarital();
        case ANNUALINCOME:
            return getAnnualIncome();
        case OCCUPATION:
            return getOccupation();
        case RESADDRESS1:
            return getResAddress1();
        case RESADDRESS2:
            return getResAddress2();
        case RESCITY:
            return getResCity();
        case RESDISTRICT:
            return getResDistrict();
        case RESSTATE:
            return getResState();
        case RESCOUNTRY:
            return getResCountry();
        case RESPINCODE:
            return getResPincode();
        case PERADDRESS1:
            return getPerAddress1();
        case PERADDRESS2:
            return getPerAddress2();
        case PERCITY:
            return getPerCity();
        case PERDISTRICT:
            return getPerDistrict();
        case PERSTATE:
            return getPerState();
        case PERCOUNTRY:
            return getPerCountry();
        case PERPINCODE:
            return getPerPincode();
        case ACCTYPE:
            return getAccType();
        case PREFCITY:
            return getPrefCity();
        case BRANCH:
            return getBranch();
        case DOCNAME:
            return getDocName();
        case APPLDATE:
            return getApplDate();
        case MANAGED:
            return getmanaged();
        case ADDRESS1:
            return getaddress1();
        case ADDRESS2:
            return getaddress2();
        case CITY:
            return getcity();
        case DISTRICT:
            return getdistrict();
        case COUNTRY:
            return getcountry();
        case PINCODE:
            return getpincode();
        case STATE:
            return getstate();
        case PERADD:
            return getperadd();
        case PERADD1:
            return getperadd1();
        case PERADDRN:
            return getperaddrn();
        case PERADDRN1:
            return getperaddrn1();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case USERID:
            setUserId((String)value);
            return;
        case PASSWORD:
            setPassword((String)value);
            return;
        case FIRSTNAME:
            setFirstName((String)value);
            return;
        case MIDDLENAME:
            setMiddleName((String)value);
            return;
        case LASTNAME:
            setLastName((String)value);
            return;
        case MOBILENO:
            setMobileNo((Number)value);
            return;
        case EMAILID:
            setEmailId((String)value);
            return;
        case REFNAME:
            setRefName((String)value);
            return;
        case DOB:
            setDob((Date)value);
            return;
        case GENDER:
            setGender((String)value);
            return;
        case PAN:
            setPan((String)value);
            return;
        case MARITAL:
            setMarital((String)value);
            return;
        case ANNUALINCOME:
            setAnnualIncome((String)value);
            return;
        case OCCUPATION:
            setOccupation((String)value);
            return;
        case RESADDRESS1:
            setResAddress1((String)value);
            return;
        case RESADDRESS2:
            setResAddress2((String)value);
            return;
        case RESCITY:
            setResCity((String)value);
            return;
        case RESDISTRICT:
            setResDistrict((String)value);
            return;
        case RESSTATE:
            setResState((String)value);
            return;
        case RESCOUNTRY:
            setResCountry((String)value);
            return;
        case RESPINCODE:
            setResPincode((Number)value);
            return;
        case PERADDRESS1:
            setPerAddress1((String)value);
            return;
        case PERADDRESS2:
            setPerAddress2((String)value);
            return;
        case PERCITY:
            setPerCity((String)value);
            return;
        case PERDISTRICT:
            setPerDistrict((String)value);
            return;
        case PERSTATE:
            setPerState((String)value);
            return;
        case PERCOUNTRY:
            setPerCountry((String)value);
            return;
        case PERPINCODE:
            setPerPincode((Number)value);
            return;
        case ACCTYPE:
            setAccType((String)value);
            return;
        case PREFCITY:
            setPrefCity((String)value);
            return;
        case BRANCH:
            setBranch((String)value);
            return;
        case DOCNAME:
            setDocName((String)value);
            return;
        case APPLDATE:
            setApplDate((Date)value);
            return;
        case MANAGED:
            setmanaged((Boolean)value);
            return;
        case ADDRESS1:
            setaddress1((Boolean)value);
            return;
        case ADDRESS2:
            setaddress2((Boolean)value);
            return;
        case CITY:
            setcity((Boolean)value);
            return;
        case DISTRICT:
            setdistrict((Boolean)value);
            return;
        case COUNTRY:
            setcountry((Boolean)value);
            return;
        case PINCODE:
            setpincode((Boolean)value);
            return;
        case STATE:
            setstate((Boolean)value);
            return;
        case PERADD:
            setperadd((Boolean)value);
            return;
        case PERADD1:
            setperadd1((Boolean)value);
            return;
        case PERADDRN:
            setperaddrn((Boolean)value);
            return;
        case PERADDRN1:
            setperaddrn1((Boolean)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
